app/api/urls.py
from django.urls import path

from .views import PatientList, PatientCreate,PatientDetail, DoctorList, DoctorCreate, DoctorDetail, LabList, LabCreate, LabDetail, UserList, UserDetail

urlpatterns = [
    path('patients/', PatientList.as_view()),
    path('patients/new/', PatientCreate.as_view()),
    path('patient/<uuid:pk>/', PatientDetail.as_view()),
    path('doctors/', DoctorList.as_view()),
    path('doctors/new/', DoctorCreate.as_view()),
    path('doctors/<uuid:pk>', DoctorDetail.as_view()),
    path('lab/', LabList.as_view()),
    path('lab/new/', LabCreate.as_view()),
    path('lab/<uuid:pk>', LabDetail.as_view()),
    path('users/', UserList.as_view()),
    path('user/<uuid:pk>', UserDetail.as_view()),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('only_sure_admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('api/', include('api.urls')),
    path('api/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, 
        document_root=settings.STATIC_ROOT
    )

app/main/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


gender_choices = [
    ('male', 'Male'),
    ('female', 'Female')
]

marriage_choices = [
    ('married', 'Married'),
    ('single', 'Single')
]

class Patient(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    middle_name = models.CharField(max_length=50, blank=True, default='')
    hospital_id = models.CharField(max_length=64, unique=True, blank=True)

    age = models.IntegerField(blank=False)

    # The first element in each tuple is the actual value to be set on the model, and the second element is the human-readable name.
    
    sex = models.CharField(max_length=6, choices=gender_choices, default='female')
    # state of origin wasn't populated with choices because it'd be too long, the form would be customized instead
    # this thread might be useful: https://stackoverflow.com/questions/66302329/how-to-create-dropdown-box-with-forms-modelform-in-django
    nationality = models.CharField(max_length=50, blank=False)
    state_of_origin = models.CharField(max_length=50, blank=False)
    marriage_status = models.CharField(max_length=10, choices=marriage_choices, default='single')
    address = models.CharField(max_length=300, blank=False)
    religion = models.CharField(max_length=50, blank=False)
    tribe =  models.CharField(max_length=50, blank=False)
    

    def __str__(self):
        return f' {self.hospital_id} --> {self.first_name}  {self.last_name}'

    def get_absolute_url(self):
        return reverse('patient_detail', args=[str(self.id)])

class DoctorAppointmentHistory(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    hospital_section = models.CharField(max_length=50, blank=False)

    # appointment report section (a fieldset and legend can be used in the form)
    presenting_complain = models.TextField(default='', blank=True)
    history_of_presenting_complain = models.TextField(default='', blank=True)
    past_medical_and_surgical_history = models.TextField(default='', blank=True)
    drugs_and_allergies = models.TextField(default='', blank=True)
    family_and_social_history = models.TextField(default='', blank=True)
    other_history = models.TextField(default='', blank=True)
    provisional_diagnosis = models.TextField(default='', blank=True)
    physical_examination = models.TextField(default='', blank=True)
    # end of appointment report section

    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    lab_appointment = models.TextField(default='None')
    next_appointment_date = models.DateField(blank=True, null=True,)

    def __str__(self):
        return f'{self.patient} --> {self.date}'

    def get_absolute_url(self):
        return reverse('patient_detail', args=[str(self.patient.id)])

    class Meta:
        ordering = ['-date']


class LabAppointmentHistory(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    report = models.TextField(blank=False)
    image_report = models.FileField(blank=True)
    next_appointment_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.patient} --> {self.date}'

    def get_absolute_url(self):
        return reverse('patient_detail', args=[str(self.patient.id)])
    
    class Meta:
        ordering = ['-date']

app/templates/patient/delete_patient.html
{% extends 'base.html' %}

{% block content %}
    <div class="container d-flex justify-content-center align-items-center vh-100" id="last_div">
        <form class="" action="" method="post"> {% csrf_token %}
            <div class="text-center mb-4">
                <p class="fs-3">Are you sure you want to delete patient?</p>
                <input class="d-inline-block m-1 button btn-danger squared" type="submit" value="Confirm">
                <a class="link d-inline-block m-1 button btn-dark squared" href="{% url 'patient_detail' patient.pk %}">Go Back</a>
            </div>
            
        </form>
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/patient/edit_patient.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-4">
        <form class="center-form width-100" action="" method="post"> {% csrf_token %}
            <p class="text-center fs-3">Update record for: {{patient.hospital_id}}</p>
            <div class="container mt-3">
                <label for="id_first_name">First Name: <span class="text-danger">*</span></label>
                <div class="">{{ form.first_name }}</div>
            </div>
            <div class="container mt-3">
                <label for="id_middle_name">Middle Name: </label>
                <div class="">{{ form.middle_name }}</div>
            </div>

            <div class="container mt-3">
                <label for="id_last_name">Last Name: <span class="text-danger">*</span></label>
                 <div class="">{{ form.last_name }}</div>
            </div>

            <div class="container mt-3">
                <div class="row">
                    <div class="col">
                        <label for="id_age">Age: <span class="text-danger">*</span></label>
                        <div class="">{{ form.age}}</div>
                    </div>
                    <div class="col">
                        <label for="id_sex">Sex: <span class="text-danger">*</span></label>
                        <div class="">{{ form.sex }}</div>
                    </div>
                </div>
            </div>
            
            <div class="container mt-3">
                <label for="id_nationality">Nationality: <span class="text-danger">*</span></label>
                <div class="">{{ form.nationality}}</div>
            </div>
            
            <div class="container mt-3">
                <div class="row">
                    <div class="col">
                        <label for="id_state_of_origin">State of Origin: <span class="text-danger">*</span></label>
                        <div class="">{{ form.state_of_origin }}</div>
                    </div>
                    <div class="col">
                        <label for="id_tribe">Tribe: <span class="text-danger">*</span></label>
                    <div class="">{{ form.tribe }}</div>
                    </div>
                </div>
            </div>

            <div class="container mt-3">
                <div class="row">
                    <div class="col">
                        <label for="id_marriage_status">Marriage Status: <span class="text-danger">*</span></label>
                        <div class="">{{ form.marriage_status }}</div>
                    </div>
                    <div class="col">
                        <label for="id_religion">Religion: <span class="text-danger">*</span></label>
                        <div class="">{{ form.religion }}</div>
                    </div>
                </div>
            </div>

            <div class="container mt-3">
                <label for="id_address">Home Address: <span class="text-danger">*</span></label>
                <div class="">{{ form.address }}</div>
            </div>
            <div class="container mt-4" id="last_div">
                <input class="button squared button-dark" type="submit" value="Update Record">
            </div>
        </form>
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/patient/new_patient.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-4">
        <form class="center-form width-100" action="" method="post"> {% csrf_token %}
            <p class="text-center fs-3">Register a new patient</p>
            <div class="container mt-3">
                <label for="id_first_name">First Name: <span class="text-danger">*</span></label>
                <div class="">{{ form.first_name }}</div>
            </div>
            <div class="container mt-3">
                <label for="id_middle_name">Middle Name: </label>
                <div class="">{{ form.middle_name }}</div>
            </div>

            <div class="container mt-3">
                <label for="id_last_name">Last Name: <span class="text-danger">*</span></label>
                <div class="">{{ form.last_name }}</div>
            </div>

            <div class="container mt-3">
                <div class="row">
                    <div class="col">
                        <label for="id_age">Age: <span class="text-danger">*</span></label>
                        <div class="">{{ form.age}}</div>
                    </div>
                    <div class="col">
                        <label for="id_sex">Sex: <span class="text-danger">*</span></label>
                        <div class="">{{ form.sex }}</div>
                    </div>
                </div>
            </div>
            
            <div class="container mt-3">
                <label for="id_nationality">Nationality: <span class="text-danger">*</span></label>
                <div class="">{{ form.nationality}}</div>
            </div>
            
            <div class="container mt-3">
                <div class="row">
                    <div class="col">
                        <label for="id_state_of_origin">State of Origin: <span class="text-danger">*</span></label>
                        <div class="">{{ form.state_of_origin }}</div>
                    </div>
                    <div class="col">
                        <label for="id_tribe">Tribe: <span class="text-danger">*</span></label>
                    <div class="">{{ form.tribe }}</div>
                    </div>
                </div>
            </div>

            <div class="container mt-3">
                <div class="row">
                    <div class="col">
                        <label for="id_marriage_status">Marriage Status: <span class="text-danger">*</span></label>
                        <div class="">{{ form.marriage_status }}</div>
                    </div>
                    <div class="col">
                        <label for="id_religion">Religion: <span class="text-danger">*</span></label>
                        <div class="">{{ form.religion }}</div>
                    </div>
                </div>
            </div>

            <div class="container mt-3">
                <label for="id_address">Home Address: <span class="text-danger">*</span></label>
                <div class="">{{ form.address }}</div>
            </div>
            <div class="container mt-4" id="last_div">
                <input class="button squared button-dark" type="submit" value="Create Record">
            </div>
        </form>
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/patient/patient_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container py-4">
        <p class="fs-3 text-center mb-4">{{patient.hospital_id}}</p>
        <div class="row w-75 center-container mx-auto my-2">
            <div class="col-sm-3">Full Name:</div>
            <div class="col-sm-6 border-bottom">{{patient.last_name}}, {{patient.middle_name}} {{patient.first_name}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Age:</div>
            <div class="col-sm-6 border-bottom">{{patient.age}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Hospital Number:</div>
            <div class="col-sm-6 border-bottom">{{patient.hospital_id}}</div>
        </div>
        
        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Sex:</div>
            <div class="col-sm-3 border-bottom">{{patient.sex}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Marriage Status:</div>
            <div class="col-sm-3 border-bottom">{{patient.marriage_status}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Home Address:</div>
            <div class="col-sm-6 border-bottom">{{patient.address}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Nationality:</div>
            <div class="col-sm-6 border-bottom">{{patient.nationality}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">State of Origin:</div>
            <div class="col-sm-6 border-bottom">{{patient.state_of_origin}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Tribe:</div>
            <div class="col-sm-6 border-bottom">{{patient.tribe}}</div>
        </div>

        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-3">Religion:</div>
            <div class="col-sm-6 border-bottom">{{patient.religion}}</div>
        </div>
        <div class="row w-75 mx-auto center-container my-2">
            <div class="col-sm-5 mx-auto py-4 text-end text-center-sm"> <!--text-start-sm is my custom class-->
                <a class="link button btn-dark squared" href="{% url 'patient_edit' patient.pk %}">Update Record</a>
            </div>
            <div class="col-sm-5 mx-auto py-4 text-center-sm">
                <a class="link button btn-danger squared" href="{% url 'patient_delete' patient.pk %}">Delete Record</a>
            </div>
        </div>
    </div>

    <div class="w-75 center-container mx-auto">
        <p class="fs-4 text-center border-bottom py-4">Appointments History:</p>
        <p class="fs-5 text-center">Doctors:</p>
        <div class="container-fluid py-4 border-bottom">
            {% if doctor_appointments %}
            <div class="row container justify-content-md-center">
                {% for meeting in doctor_appointments %}
                <div class="col-sm-3 border shadow py-2 mx-2">
                    <p class="text-secondary">{{meeting.date}}</p>
                    <p class="text-secondary"> Created by: {{meeting.created_by}}</p>
                    <p class="text-center">
                        <a class="link button button-dark squared px-4" href="{% url 'doctor_detail' meeting.pk %}">View</a>
                        <a class="link btn-danger squared px-4" href="{% url 'doctor_delete' meeting.pk %}">Delete</a>
                    </p>
                </div>
                {% endfor %}        
            </div>
            {% else %}
                <div class="container w-25">
                    <img src="{% static 'images/blank-note.png' %}" alt="" class="img-fluid">
                    <p class="fs-6 text-center text-secondary">Nothing to show yet</p> 
                </div>
            {% endif %}
            <div class="text-center mt-4">
                <a class="link btn-success squared" href="{% url 'doctor_new' patient.pk %}"> + Add new</a>
            </div>
        </div> 
        
        <p class="fs-5 text-center">Laboratory:</p>
        <div class="container-fluid border-bottom py-4">
            {% if lab_appointments %}
            <div class="row container justify-content-md-center">
                {% for meeting in lab_appointments %}
                <div class="col-sm-3 border shadow py-2 mx-2">
                    <p class="text-secondary">{{meeting.date}}</p>
                    <p class="text-secondary"> Created by: {{meeting.created_by}}</p>
                    <p class="text-center"> 
                        <a class="link button button-dark squared px-4" href="{% url 'lab_detail' meeting.pk %}">View</a>
                        <a class="link btn-danger squared px-4" href="{% url 'lab_delete' meeting.pk %}">Delete</a>
                    </p>
                </div>
                {% endfor %}        
            </div>
            
            {% else %}
            <div class="container w-25">
                <img src="{% static 'images/blank-note.png' %}" alt="" class="img-fluid">
                <p class="fs-6 text-center text-secondary">Nothing to show yet</p> 
            </div>
            {% endif %}
            <div class="text-center mt-4" id="last_div">
                <a class="link btn-success squared" href="{% url 'lab_new' patient.pk %}">+ Add new</a>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/patient/patient_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid py-4">
        {% if patient_list %}
            <div class="row container-fluid justify-content-md-center w-100 mx-auto" id="last_div">
                {% for patient in patient_list %}
                <div class="col-sm-3 border shadow py-1 m-2">
                    <p class="text-secondary lh-sm"><small>{{patient.last_name}}, {{patient.middle_name}} {{patient.first_name}}</small></p>
                    <p class="text-secondary lh-sm"><small>{{patient.hospital_id}}</small></p>
                    <p class="text-secondary lh-sm"><small>{{patient.age}} Years</small></p>

                    <p class="text-center"> 
                        <a class="link button button-dark squared px-4 d-inline-block my-1" href="{% url 'patient_detail' patient.pk %}">View</a>
                    </p>
                </div>
                {% endfor %}        
            </div>
        {% else %}
            <div class="container w-50 mx-auto" id="last_div">
                <img src="{% static 'images/blank-note.png' %}" alt="" class="img-fluid">
                <p class="fs-6 text-center text-secondary">Nothing to show Here</p> 
            </div>
        {% endif %}
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/patient/patient_search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid py-4">
        {% if patients %}
            <div class="row container-fluid justify-content-md-center w-100 mx-auto" id="last_div">
                {% for patient in patients %}
                    <div class="col-sm-3 border shadow py-1 m-2">
                        <p class="text-secondary lh-sm"><small>{{ patient.hospital_id }}</small></p>
                        <p class="text-secondary lh-sm"><small>{{patient.last_name}}, {{patient.middle_name}} {{patient.first_name}}</small></p> 
                        <p class="text-secondary lh-sm"><small>{{patient.age}}</small></p>
                        <p class="text-secondary lh-sm"><small>{{ patient.sex }}</small></p>
                        <p class="text-center"> 
                            <a class="link button button-dark squared px-4 d-inline-block my-1" href="{% url 'patient_detail' patient.pk %}">View</a>
                        </p>
                        
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="container w-50 mx-auto" id="last_div">
                <img src="{% static 'images/blank-note.png' %}" alt="" class="img-fluid">
                <p class="fs-6 text-center text-secondary">Nothing to show Here</p> 
            </div>
        {% endif %}
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}