app/api/urls.py
from django.urls import path

from .views import PatientList, PatientCreate,PatientDetail, DoctorList, DoctorCreate, DoctorDetail, LabList, LabCreate, LabDetail, UserList, UserDetail

urlpatterns = [
    path('patients/', PatientList.as_view()),
    path('patients/new/', PatientCreate.as_view()),
    path('patient/<uuid:pk>/', PatientDetail.as_view()),
    path('doctors/', DoctorList.as_view()),
    path('doctors/new/', DoctorCreate.as_view()),
    path('doctors/<uuid:pk>', DoctorDetail.as_view()),
    path('lab/', LabList.as_view()),
    path('lab/new/', LabCreate.as_view()),
    path('lab/<uuid:pk>', LabDetail.as_view()),
    path('users/', UserList.as_view()),
    path('user/<uuid:pk>', UserDetail.as_view()),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('only_sure_admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('api/', include('api.urls')),
    path('api/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, 
        document_root=settings.STATIC_ROOT
    )

app/main/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


gender_choices = [
    ('male', 'Male'),
    ('female', 'Female')
]

marriage_choices = [
    ('married', 'Married'),
    ('single', 'Single')
]

class Patient(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    middle_name = models.CharField(max_length=50, blank=True, default='')
    hospital_id = models.CharField(max_length=64, unique=True, blank=True)

    age = models.IntegerField(blank=False)

    # The first element in each tuple is the actual value to be set on the model, and the second element is the human-readable name.
    
    sex = models.CharField(max_length=6, choices=gender_choices, default='female')
    # state of origin wasn't populated with choices because it'd be too long, the form would be customized instead
    # this thread might be useful: https://stackoverflow.com/questions/66302329/how-to-create-dropdown-box-with-forms-modelform-in-django
    nationality = models.CharField(max_length=50, blank=False)
    state_of_origin = models.CharField(max_length=50, blank=False)
    marriage_status = models.CharField(max_length=10, choices=marriage_choices, default='single')
    address = models.CharField(max_length=300, blank=False)
    religion = models.CharField(max_length=50, blank=False)
    tribe =  models.CharField(max_length=50, blank=False)
    

    def __str__(self):
        return f' {self.hospital_id} --> {self.first_name}  {self.last_name}'

    def get_absolute_url(self):
        return reverse('patient_detail', args=[str(self.id)])

class DoctorAppointmentHistory(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    hospital_section = models.CharField(max_length=50, blank=False)

    # appointment report section (a fieldset and legend can be used in the form)
    presenting_complain = models.TextField(default='', blank=True)
    history_of_presenting_complain = models.TextField(default='', blank=True)
    past_medical_and_surgical_history = models.TextField(default='', blank=True)
    drugs_and_allergies = models.TextField(default='', blank=True)
    family_and_social_history = models.TextField(default='', blank=True)
    other_history = models.TextField(default='', blank=True)
    provisional_diagnosis = models.TextField(default='', blank=True)
    physical_examination = models.TextField(default='', blank=True)
    # end of appointment report section

    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    lab_appointment = models.TextField(default='None')
    next_appointment_date = models.DateField(blank=True, null=True,)

    def __str__(self):
        return f'{self.patient} --> {self.date}'

    def get_absolute_url(self):
        return reverse('patient_detail', args=[str(self.patient.id)])

    class Meta:
        ordering = ['-date']


class LabAppointmentHistory(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    report = models.TextField(blank=False)
    image_report = models.FileField(blank=True)
    next_appointment_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.patient} --> {self.date}'

    def get_absolute_url(self):
        return reverse('patient_detail', args=[str(self.patient.id)])
    
    class Meta:
        ordering = ['-date']

app/templates/doctor/appointment_search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid py-4">
        {% if doctor_appointments %}
        <div class="row container-fluid justify-content-md-center w-100 mx-auto" id="last_div">
            {% for appointment in doctor_appointments %}
                <div class="col-sm-3 border shadow py-1 m-2">
                    <p class="text-secondary lh-sm"><small>{{appointment.date}}</small></p>
                    <p class="text-secondary lh-sm"><small>{{appointment.patient.last_name}}, {{appointment.patient.middle_name}} {{appointment.patient.first_name}}</small></p>
                    <p class="text-secondary lh-sm"><small>{{appointment.patient.hospital_id}}</small></p>
                    <p class="text-secondary lh-sm"><small>{{appointment.hospital_section}}</small></p>

                    <p class="text-center"> 
                        <a class="link button button-dark squared px-4 d-inline-block my-1" href="{% url 'doctor_detail' appointment.pk %}">View</a>
                    </p>
                </div> 
            {% endfor %}
        </div>
        {% else %}
            <div class="container w-50 mx-auto" id="last_div">
                <img src="{% static 'images/blank-note.png' %}" alt="" class="img-fluid">
                <p class="fs-6 text-center text-secondary">Nothing to show Here</p> 
            </div>
        {% endif %}
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/doctor/delete_doctor_appointment.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100" id="last_div">
    <form class="" action="" method="post"> {% csrf_token %}
        <div class="text-center mb-4">
            <p class="fs-3">Are you sure you want to remove record???</p>
            <input class="d-inline-block m-1 button btn-danger squared" type="submit" value="Confirm">
            <a class="link d-inline-block m-1 button btn-dark squared" href="{% url 'doctor_detail' doctor_appointment.pk %}">Go Back</a>
        </div>
        
    </form>
</div>
    
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/doctor/doctor_appointment_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-4">
        <p class="fs-3 text-center mb-4">{{doctor_appointment.patient.hospital_id}}</p>
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Patient:</div>
            <div class="col-sm-6 border-bottom">{{ doctor_appointment.patient}}</div>
        </div>

        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Date:</div>
            <div class="col-sm-6 border-bottom">{{ doctor_appointment.date }}</div>
        </div>

        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Section:</div>
            <div class="col-sm-6 border-bottom">{{ doctor_appointment.hospital_section }}</div>
        </div>
        
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Created By:</div>
            <div class="col-sm-6 border-bottom">{{ doctor_appointment.created_by }}</div>
        </div>

        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Presenting Complain:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.presenting_complain }}</div>
        </div>
        
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">History of Presenting Complain:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.history_of_preseting_complain }}</div>
        </div>

        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Past Medical and Surgical History:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.past_medical_and_surgical_history }}</div>
        </div>
        
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Drugs and Allergies:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.drugs_and_allergies }}</div>
        </div>
        
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Family and Social History:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.family_and_social_history }}</div>
        </div>

        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Other History:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.other_history }}</div>
        </div>
        
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Provisional Diagnosis:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.provisional_diagnosis }}</div>
        </div>

        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Physical Examination:</div>
            <div class="col-sm-6 border py-2">{{ doctor_appointment.physical_examination }}</div>
        </div>
        
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Created By:</div>
            <div class="col-sm-6 border-bottom">{{ doctor_appointment.created_by }}</div>
        </div>
        
        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Lab Appointment:</div>
            <div class="col-sm-6 border-bottom">{{ doctor_appointment.lab_appointment }}</div>
        </div>

        <div class="row w-75 center-container mx-auto my-3">
            <div class="col-sm-3">Next Appointment:</div>
            <div class="col-sm-6 border-bottom">{{ doctor_appointment.next_appointment_date }}</div>
        </div>
        
        <div class="row w-75 mx-auto center-container my-3" id="last_div">
            <div class="col-sm-5 mx-auto py-4 text-end text-center-sm"> <!--text-start-sm is my custom class-->
                <a class="link button btn-dark squared" href="{% url 'doctor_edit' doctor_appointment.pk %}">Update Record</a>
            </div>
            <div class="col-sm-5 mx-auto py-4 text-center-sm">
                <a class="link button btn-danger squared" href="{% url 'doctor_delete' doctor_appointment.pk %}">Delete Record</a>
            </div>
        </div>
        <!-- <a href="{% url 'doctor_edit' doctor_appointment.pk %}">Update Record</a> -->
        <!-- <a href="{% url 'doctor_delete' doctor_appointment.pk %}">Delete Record</a> -->
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/doctor/doctor_appointment_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid py-4">
        {% if doctor_appointment_list %}
        <div class="row container-fluid justify-content-md-center w-100 mx-auto" id="last_div">
            {% for appointment in doctor_appointment_list %}
            <div class="col-sm-3 border shadow py-1 m-2">
                <p class="text-secondary lh-sm"><small>{{appointment.date}}</small></p>
                <p class="text-secondary lh-sm"><small>{{appointment.patient.last_name}}, {{appointment.patient.middle_name}} {{appointment.patient.first_name}}</small></p>
                <p class="text-secondary lh-sm"><small>{{appointment.patient.hospital_id}}</small></p>
                <p class="text-secondary lh-sm"><small>{{appointment.hospital_section}}</small></p>

                <p class="text-center"> 
                    <a class="link button button-dark squared px-4 d-inline-block my-1" href="{% url 'doctor_detail' appointment.pk %}">View</a>
                </p>
            </div>
            {% endfor %}
        </div>
            
        {% else %}
            <div class="container w-50 mx-auto" id="last_div">
                <img src="{% static 'images/blank-note.png' %}" alt="" class="img-fluid">
                <p class="fs-6 text-center text-secondary">Nothing to show Here</p> 
            </div>
        {% endif %}
    </div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/doctor/edit_doctor_appointment.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <p class="text-center fs-3">Create New Record</p>
    <form class="center-form width-100" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container mt-3">
            <label for="id_hospital_section">Hospital Section:
        </div>
        <div class="container">{{ form.hospital_section }}</div>

        <div class="container mt-3">
            <label for="id_presenting_complain">Presenting Compain:
        </div>
        <div class="container">{{ form.presenting_complain }}</div>

        <div class="container mt-3">
            <label for="id_history_of_presenting_complain">History of Presenting Complain:
        </div>
        <div class="container">{{ form.history_of_presenting_complain }}</div>

        <div class="container mt-3">
            <label for="id_past_medical_and_surgical_history">Past medical and Surgical History:
        </div>
        <div class="container">{{ form.past_medical_and_surgical_history  }}</div>

        <div class="container mt-3">
            <label for="id_drugs_and_allergies">Drugs and Allergies:
        </div>
        <div class="container">{{ form.drugs_and_allergies }}</div>

        <div class="container mt-3">
            <label for="id_family_and_social_history">Family and Social History:
        </div>
        <div class="container">{{ form.family_and_social_history }}</div>

        <div class="container mt-3">
            <label for="id_other_history">Other History:
        </div>
        <div class="container">{{ form.other_history }}</div>

        <div class="container mt-3">
            <label for="id_provisional_diagnosis">Provisional Diagnosis:
        </div>
        <div class="container">{{ form.provisional_diagnosis }}</div>

        <div class="container mt-3">
            <label for="id_physical_examination">Physical Examination:
        </div>
        <div class="container">{{ form.physical_examination }}</div>


        <div class="container mt-3">
            <label for="id_physical_examination">Lab Appointment:
        </div>
        <div class="container">{{ form.lab_appointment }}</div>
        
        <div class="container mt-3">
            <label for="id_patient">Next Appointment:
            <div class="">{{ form.next_appointment_date }}</div>
        </div>
        
        <div class="container mt-4" id="last_div">
            <input class="button squared button-dark" type="submit" value="Update Record">
        </div>
    </form>
</div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}

app/templates/doctor/new_doctor_appointment.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <p class="text-center fs-3">Create New Record</p>
    <form class="center-form width-100" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container-fluid mt-3">
            <label for="id_patient">Patient:
        </div>
        <div class="container">{{ form.patient }}</div>
        

        <div class="container mt-3">
            <label for="id_hospital_section">Hospital Section:
        </div>
        <div class="container">{{ form.hospital_section }}</div>

        <div class="container mt-3">
            <label for="id_presenting_complain">Presenting Compain:
        </div>
        <div class="container">{{ form.presenting_complain }}</div>

        <div class="container mt-3">
            <label for="id_history_of_presenting_complain">History of Presenting Complain:
        </div>
        <div class="container">{{ form.history_of_presenting_complain }}</div>

        <div class="container mt-3">
            <label for="id_past_medical_and_surgical_history">Past medical and Surgical History:
        </div>
        <div class="container">{{ form.past_medical_and_surgical_history  }}</div>

        <div class="container mt-3">
            <label for="id_drugs_and_allergies">Drugs and Allergies:
        </div>
        <div class="container">{{ form.drugs_and_allergies }}</div>

        <div class="container mt-3">
            <label for="id_family_and_social_history">Family and Social History:
        </div>
        <div class="container">{{ form.family_and_social_history }}</div>

        <div class="container mt-3">
            <label for="id_other_history">Other History:
        </div>
        <div class="container">{{ form.other_history }}</div>

        <div class="container mt-3">
            <label for="id_provisional_diagnosis">Provisional Diagnosis:
        </div>
        <div class="container">{{ form.provisional_diagnosis }}</div>

        <div class="container mt-3">
            <label for="id_physical_examination">Physical Examination:
        </div>
        <div class="container">{{ form.physical_examination }}</div>

        <div class="container mt-3">
            <label for="id_physical_examination">Lab Appointment:
        </div>
        <div class="container">{{ form.lab_appointment }}</div>
        
        <div class="container mt-3">
            <label for="id_patient">Next Appointment:
            <div class="">{{ form.next_appointment_date }}</div>
        </div>
        
        <div class="container mt-4" id="last_div">
            <input class="button squared button-dark" type="submit" value="Create Record">
        </div>
    </form>
</div>
{% endblock content %}

{% block js %}
    <script>
        var last_div_pos = document.querySelector('#last_div').getBoundingClientRect();
        var footer =  document.querySelector('.footer');
        var footer_pos = footer.getBoundingClientRect();
        if (last_div_pos.bottom >= footer_pos.top) { // if there is an overlap
            footer.classList.remove("fixed-bottom");
        }
    </script>
{% endblock js %}